/* NEXORA HQ — renders window.NX (data.js, generated by build_hq.py) into a local single-page dashboard. */
(function () {
  const D = window.NX || {};
  const $ = (s, el = document) => el.querySelector(s);
  const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const store = {
    get(k, d) { try { const v = localStorage.getItem(k); return v == null ? d : JSON.parse(v); } catch (e) { return d; } },
    set(k, v) { try { localStorage.setItem(k, JSON.stringify(v)); } catch (e) { /* private mode */ } },
  };
  const TOPIC = { network: 'var(--network)', security: 'var(--security)', smart: 'var(--smart)', digital: 'var(--digital)', sun: 'var(--sun)' };
  const STATUS = { published: 'Publié', ready: 'Prêt à publier', archive: 'Archive', internal: 'Interne', other: 'Autre compte' };
  const I = (d) => `<svg viewBox="0 0 24 24">${d}</svg>`;
  const ICON = {
    home: I('<path d="M3 11l9-7 9 7"/><path d="M5 10v10h14V10"/>'),
    ig: I('<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/>'),
    video: I('<rect x="3" y="5" width="14" height="14" rx="3"/><path d="M17 10l4-2.5v9L17 14"/>'),
    posts: I('<rect x="3" y="3" width="8" height="8" rx="2"/><rect x="13" y="3" width="8" height="8" rx="2"/><rect x="3" y="13" width="8" height="8" rx="2"/><rect x="13" y="13" width="8" height="8" rx="2"/>'),
    stories: I('<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 6h4"/>'),
    offer: I('<path d="M20 12l-8 8-9-9V3h8z"/><circle cx="7.5" cy="7.5" r="1.5"/>'),
    brand: I('<circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 0 0 18"/><circle cx="8" cy="10" r="1"/><circle cx="12" cy="7" r="1"/><circle cx="16" cy="10" r="1"/>'),
    info: I('<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7.5v.5"/>'),
    docs: I('<path d="M6 2h9l5 5v15H6z"/><path d="M14 2v6h6M9 13h8M9 17h6"/>'),
    journal: I('<path d="M4 5h16M4 12h16M4 19h10"/>'),
    cam: I('<path d="M3 7l13-3 1.5 6L4.5 13z"/><path d="M10 11.5l1 4.5h-5"/><circle cx="13" cy="8.2" r="1.3"/>'),
    wa: I('<path d="M12 3a9 9 0 0 0-7.7 13.6L3 21l4.5-1.2A9 9 0 1 0 12 3z"/><path d="M9 8.5c0 3.6 2.9 6.5 6.5 6.5l1-1.6-2-1-1 1a4.5 4.5 0 0 1-2.4-2.4l1-1-1-2z"/>'),
    ext: I('<path d="M14 4h6v6M20 4l-9 9M18 14v6H4V6h6"/>'),
    copy: I('<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3"/>'),
    dl: I('<path d="M12 4v11M7 10l5 5 5-5M5 20h14"/>'),
    git: I('<path d="M9 19c-4 1.5-4-2-6-2.5M15 21v-3.5c0-1 .1-1.4-.5-2 2.8-.3 5.5-1.4 5.5-6a4.6 4.6 0 0 0-1.3-3.2 4.2 4.2 0 0 0-.1-3.2s-1.1-.3-3.5 1.3a12 12 0 0 0-6.2 0C6.5 2.8 5.4 3.1 5.4 3.1a4.2 4.2 0 0 0-.1 3.2A4.6 4.6 0 0 0 4 9.5c0 4.6 2.7 5.7 5.5 6-.6.6-.6 1.2-.5 2V21"/>'),
  };

  const ready = (arr) => arr.filter((x) => x.status === 'ready').length;
  const nReady = ready(D.videos || []) + ready(D.carousels || []) + ready(D.tips || []) + ready(D.stories || []);
  const SECTIONS = [
    ['accueil', 'Accueil', ICON.home, null],
    ['instagram', 'Instagram', ICON.ig, D.ig ? (D.ig.account || {}).followers_count : null],
    ['videos', 'Vidéos', ICON.video, (D.videos || []).length],
    ['posts', 'Posts', ICON.posts, (D.carousels || []).length + (D.tips || []).length],
    ['stories', 'Stories', ICON.stories, (D.stories || []).length],
    ['cameras', 'Caméras', ICON.cam, ((D.cameras || {}).cameras || []).length],
    ['offre', 'Offre & prix', ICON.offer, null],
    ['marque', 'Marque', ICON.brand, null],
    ['infos', 'Infos utiles', ICON.info, null],
    ['docs', 'Documents', ICON.docs, (D.docs || []).length],
    ['journal', 'Journal', ICON.journal, null],
  ];

  // ---------- helpers ----------
  function toast(msg) {
    const t = $('#toast'); t.textContent = msg; t.classList.add('on');
    clearTimeout(toast.h); toast.h = setTimeout(() => t.classList.remove('on'), 1600);
  }
  function copy(text, label) {
    const done = () => toast(label || 'Copié');
    if (navigator.clipboard && window.isSecureContext) navigator.clipboard.writeText(text).then(done, () => fallback());
    else fallback();
    function fallback() {
      const ta = document.createElement('textarea'); ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0';
      document.body.appendChild(ta); ta.select();
      try { document.execCommand('copy'); done(); } catch (e) { toast('Copie impossible'); }
      ta.remove();
    }
  }
  const badge = (s) => `<span class="badge st-${esc(s)}">${esc(STATUS[s] || s)}</span>`;
  const topic = (t) => `<span class="topic" style="--c:${TOPIC[t] || TOPIC.network}"></span>`;
  const fmtDate = (iso) => { if (!iso) return ''; const d = new Date(iso.replace('+0000', 'Z')); return isNaN(d) ? iso : d.toLocaleString('fr-FR', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }); };
  const num = (v) => (v == null || v === '' ? '—' : Number(v).toLocaleString('fr-FR'));
  let CAPS = [];
  const capBlock = (text) => {
    if (!text) return '';
    const i = CAPS.push(text) - 1;
    return `<details class="cap"><summary>Légende</summary><pre>${esc(text)}</pre><button class="btn sm" type="button" data-copy="${i}">${ICON.copy}Copier la légende</button></details>`;
  };
  const head = (title, sub, actions = '') => `<div class="head"><div><h1>${title}</h1>${sub ? `<p>${sub}</p>` : ''}</div>${actions}</div>`;

  // ---------- lightbox ----------
  let LB = { list: [], i: 0 };
  let lbImg = null;
  function openLB(list, i) {
    LB = { list, i };
    if (!lbImg) { lbImg = document.createElement('img'); lbImg.alt = ''; $('#lbFig').prepend(lbImg); }
    showLB(); $('#lb').hidden = false; document.body.style.overflow = 'hidden';
  }
  function showLB() {
    const it = LB.list[LB.i]; lbImg.src = it.src; lbImg.alt = it.cap || '';
    $('#lbCap').textContent = `${it.cap || ''}${LB.list.length > 1 ? `  ·  ${LB.i + 1} / ${LB.list.length}` : ''}`;
    $('#lbPrev').style.visibility = $('#lbNext').style.visibility = LB.list.length > 1 ? 'visible' : 'hidden';
  }
  function closeLB() { $('#lb').hidden = true; document.body.style.overflow = ''; }
  const stepLB = (d) => { LB.i = (LB.i + d + LB.list.length) % LB.list.length; showLB(); };
  let GALLERIES = [];
  const gal = (list) => GALLERIES.push(list) - 1;

  // ---------- sections ----------
  function accueilPublic() {
    const n = (arr) => (arr || []).length;
    const readyItems = [
      ...(D.videos || []).filter((v) => v.status === 'ready').map((v) => ({ src: v.poster, t: v.title, go: 'videos', poster: true })),
      ...(D.carousels || []).filter((c) => c.status === 'ready').map((c) => ({ src: c.slides[0].thumb, t: c.title, go: 'posts' })),
    ].slice(0, 12);
    const kpis = [['Vidéos', n(D.videos), 'var(--security)'], ['Carrousels', n(D.carousels), 'var(--network)'], ['Tips du jour', n(D.tips), 'var(--smart)'], ['Stories', n(D.stories), 'var(--digital)']];
    return `
      <div class="hero">
        <img class="hero-logo" src="brand/logo-v2/final/nexora_icon_white.svg" alt="">
        <div class="kick">NEXORA · médias en ligne</div>
        <h1>Vidéos, posts,<br><span>logos et textes.</span></h1>
        <p>Accessible partout. Touche une vidéo pour la lire, une image pour l'agrandir, « Légende » pour copier le texte à publier.</p>
        <div class="row">
          <a class="btn white" href="${esc(D.business.ig_url)}" target="_blank" rel="noopener">${ICON.ig}${esc(D.business.instagram)}</a>
          <a class="btn glass" href="${esc(D.business.wa)}" target="_blank" rel="noopener">${ICON.wa}WhatsApp ${esc(D.business.whatsapp)}</a>
        </div>
      </div>
      <div class="grid g4" style="margin-top:18px">${kpis.map(([l, v, c]) => `<div class="card kpi" style="--c:${c}"><div class="lab"><i></i>${l}</div><div class="val">${v}</div></div>`).join('')}</div>
      <div class="h2">Prêts à publier <small>${nReady} éléments</small></div>
      <div class="grid auto-s">${readyItems.map((x) => `<a class="card media" href="#${x.go}" style="text-decoration:none"><div class="thumb"><img loading="lazy" class="${x.poster ? 'poster' : ''}" src="${esc(x.src)}" alt=""></div><div class="meta"><div class="t">${esc(x.t)}</div></div></a>`).join('')}</div>
      <div class="h2">Textes <small>fichiers complets</small></div>
      <div class="card"><div class="chips" style="margin:0">${(D.texts || []).map((t) => `<a class="chip" href="${esc(t.file)}" target="_blank" rel="noopener" style="text-decoration:none">${esc(t.title)}</a>`).join('')}</div></div>`;
  }

  function accueil() {
    if (D.public) return accueilPublic();
    const a = (D.ig && D.ig.account) || {};
    const pub = (D.videos || []).filter((v) => v.status === 'published').length;
    const done = store.get('nx-todo', {});
    const kpis = [
      ['Abonnés', num(a.followers_count), D.ig ? `snapshot du ${fmtDate(D.ig.fetched_at)}` : 'stats non chargées', 'var(--network)'],
      ['Publications', num(a.media_count), `dont ${pub} Reels`, 'var(--smart)'],
      ['Vues · 7 jours', num((((D.ig || {}).account_insights || {}).last_7_days || {}).views), 'toutes publications', 'var(--digital)'],
      ['Prêts à publier', nReady, 'vidéos, posts, tips, stories', 'var(--sun)'],
    ];
    const readyItems = [
      ...(D.videos || []).filter((v) => v.status === 'ready').map((v) => ({ src: v.poster, t: v.title, go: 'videos', poster: true })),
      ...(D.carousels || []).filter((c) => c.status === 'ready').map((c) => ({ src: c.slides[0].thumb, t: c.title, go: 'posts' })),
    ].slice(0, 10);
    return `
      <div class="hero">
        <img class="hero-logo" src="brand/logo-v2/final/nexora_icon_white.svg" alt="">
        <div class="kick">NEXORA HQ · ${esc(D.business.city)}</div>
        <h1>Tout NEXORA,<br><span>au même endroit.</span></h1>
        <p>${esc(D.business.offer)}. Vidéos, posts, stories, stats Instagram, prix et documents du projet.</p>
        <div class="row">
          <a class="btn white" href="${esc(D.business.ig_url)}" target="_blank" rel="noopener">${ICON.ig}${esc(D.business.instagram)}</a>
          <a class="btn glass" href="${esc(D.business.wa)}" target="_blank" rel="noopener">${ICON.wa}WhatsApp ${esc(D.business.whatsapp)}</a>
          <a class="btn glass" href="${esc(D.business.assets_repo)}" target="_blank" rel="noopener">${ICON.git}Dépôt des médias</a>
        </div>
      </div>
      <div class="grid g4" style="margin-top:18px">${kpis.map(([l, v, s, c]) => `<div class="card kpi" style="--c:${c}"><div class="lab"><i></i>${l}</div><div class="val">${v}</div><div class="sub">${s}</div></div>`).join('')}</div>
      <div class="grid g2" style="margin-top:18px">
        <div class="card"><div class="h2" style="margin-top:0">À faire dans l'app <small>coché = enregistré sur ce PC</small></div>
          <div class="todo">${(D.reminders || []).map((r) => `<label><input type="checkbox" data-todo="${esc(r.id)}" ${done[r.id] ? 'checked' : ''}><span>${esc(r.text)}${r.link ? `<a href="${esc(r.link)}" target="_blank" rel="noopener">ouvrir</a>` : ''}</span></label>`).join('')}</div>
        </div>
        <div class="card"><div class="h2" style="margin-top:0">Plan de publication conseillé <small>rien n'est publié automatiquement</small></div>
          <div class="plan">${(D.plan || []).map((w) => `<div class="wk"><b>${esc(w.week)}</b><ul>${w.items.map((x) => `<li>${esc(x)}</li>`).join('')}</ul></div>`).join('')}</div>
          <p class="note">Pas de publication pendant Shabbat et les fêtes. Viser 1 Reel et 2 posts par semaine, des stories la plupart des jours.</p>
        </div>
      </div>
      <div class="h2">Prêts à publier <small>${nReady} éléments</small></div>
      <div class="grid auto-s">${readyItems.map((x) => `<a class="card media" href="#${x.go}" style="text-decoration:none"><div class="thumb"><img loading="lazy" class="${x.poster ? 'poster' : ''}" src="${esc(x.src)}" alt=""></div><div class="meta"><div class="t">${esc(x.t)}</div></div></a>`).join('')}</div>
      <div class="h2">Services</div>
      <div class="grid g4">${D.business.services.map((s) => `<div class="card svc" style="--c:${TOPIC[s.topic]}"><h3>${esc(s.name)}</h3><p>${esc(s.text)}</p></div>`).join('')}</div>`;
  }

  function instagram() {
    const ig = D.ig;
    if (!ig) {
      return head('Instagram', 'Statistiques du compte') + `<div class="card empty"><b>Pas encore de stats</b>Lance <code>HQ\\update_stats.ps1</code> (clic droit → Exécuter avec PowerShell) puis recharge la page.</div>`;
    }
    const a = ig.account || {}, ins = ig.account_insights || {};
    const media = (ig.media || []).slice();
    const maxV = Math.max(1, ...media.map((m) => (m.insights || {}).views || 0));
    const tot = (k) => media.reduce((s, m) => s + ((m.insights || {})[k] || 0), 0);
    const best = media.slice().sort((x, y) => ((y.insights || {}).views || 0) - ((x.insights || {}).views || 0))[0];
    const type = (m) => (m.media_product_type === 'REELS' ? 'Reel' : m.media_type === 'CAROUSEL_ALBUM' ? 'Carrousel' : m.media_type === 'IMAGE' ? 'Image' : m.media_type);
    const w7 = ins.last_7_days || {}, w28 = ins.last_28_days || {};
    return head('Instagram', `Snapshot en lecture seule du ${fmtDate(ig.fetched_at)} · mise à jour : <code>HQ\\update_stats.ps1</code>`,
      `<a class="btn" href="${esc(D.business.ig_url)}" target="_blank" rel="noopener">${ICON.ext}Ouvrir le profil</a>`) + `
      <div class="card"><div class="profile">
        <img src="${esc(D.profile_pic)}" alt="Photo de profil NEXORA">
        <div><h2>@${esc(a.username)}</h2><div style="color:var(--muted);font-weight:600">${esc(a.name)}</div><div class="bio">${esc(a.biography)}</div>
          <div class="nums"><div><b>${num(a.followers_count)}</b><span>abonnés</span></div><div><b>${num(a.follows_count)}</b><span>abonnements</span></div><div><b>${num(a.media_count)}</b><span>publications</span></div></div></div>
      </div></div>
      <div class="grid g4" style="margin-top:18px">
        ${[['Vues · 7 j', w7.views, 'var(--digital)'], ['Comptes touchés · 7 j', w7.reach, 'var(--network)'], ['Visites du profil · 7 j', w7.profile_views, 'var(--smart)'], ['Interactions · 7 j', w7.total_interactions, 'var(--sun)']]
          .map(([l, v, c]) => `<div class="card kpi" style="--c:${c}"><div class="lab"><i></i>${l}</div><div class="val">${num(v)}</div><div class="sub">28 j : ${num(w28[{ 'Vues · 7 j': 'views', 'Comptes touchés · 7 j': 'reach', 'Visites du profil · 7 j': 'profile_views', 'Interactions · 7 j': 'total_interactions' }[l]])}</div></div>`).join('')}
      </div>
      <div class="grid g3" style="margin-top:18px">
        <div class="card kpi" style="--c:var(--network)"><div class="lab"><i></i>Vues cumulées des posts</div><div class="val">${num(tot('views'))}</div><div class="sub">${media.length} publications</div></div>
        <div class="card kpi" style="--c:var(--smart)"><div class="lab"><i></i>Enregistrements</div><div class="val">${num(tot('saved'))}</div><div class="sub">partages : ${num(tot('shares'))}</div></div>
        <div class="card kpi" style="--c:var(--sun)"><div class="lab"><i></i>Meilleure publication</div><div class="val" style="font-size:22px;line-height:1.2">${esc((D.igtitles || {})[best && best.permalink] || type(best || {}))}</div><div class="sub">${num(((best || {}).insights || {}).views)} vues</div></div>
      </div>
      <div class="h2">Publications <small>vues, portée, enregistrements</small></div>
      <div class="tablewrap"><table class="mid"><thead><tr><th>Publication</th><th>Type</th><th>Date</th><th>Vues</th><th></th><th>Portée</th><th>J'aime</th><th>Comm.</th><th>Enreg.</th></tr></thead><tbody>
        ${media.map((m) => { const s = m.insights || {}; const th = (D.igthumbs || {})[m.permalink]; const t = (D.igtitles || {})[m.permalink] || (m.caption || '').split('\n')[0];
          return `<tr><td><div class="mini">${th ? `<img loading="lazy" src="${esc(th)}" alt="">` : ''}<div><a href="${esc(m.permalink)}" target="_blank" rel="noopener" style="font-weight:700;text-decoration:none">${esc(t)}</a></div></div></td>
          <td>${esc(type(m))}</td><td style="white-space:nowrap">${esc(fmtDate(m.timestamp))}</td><td class="num">${num(s.views)}</td><td><div class="bar"><i style="width:${Math.round(100 * (s.views || 0) / maxV)}%"></i></div></td>
          <td class="num">${num(s.reach)}</td><td class="num">${num(m.like_count)}</td><td class="num">${num(m.comments_count)}</td><td class="num">${num(s.saved)}</td></tr>`; }).join('')}
      </tbody></table></div>
      ${(ig.stories || []).length ? `<p class="note">${ig.stories.length} stories actives au moment du snapshot (elles disparaissent après 24 h).</p>` : ''}
      ${(ig.notes || []).length ? `<details class="cap" style="margin-top:14px"><summary>Notes du snapshot</summary><pre>${esc(ig.notes.join('\n'))}</pre></details>` : ''}`;
  }

  function videos() {
    const list = D.videos || [];
    const f = store.get('nx-vf', 'all');
    const counts = { all: list.length, ready: ready(list), published: list.filter((v) => v.status === 'published').length, archive: list.filter((v) => ['archive', 'internal', 'other'].includes(v.status)).length };
    const shown = list.filter((v) => f === 'all' || v.status === f || (f === 'archive' && ['archive', 'internal', 'other'].includes(v.status)));
    return head('Vidéos', 'Reels en anglais avec voix off. « Produits 01 à 04 » utilisent tes vraies photos Hikvision / Provision-ISR (dossier media/videos_produits). Musique de fond optionnelle dans l’app, volume bas.') + `
      <div class="chips">${[['all', 'Toutes'], ['ready', 'Prêtes'], ['published', 'Publiées'], ['archive', 'Archives & autres']].map(([k, l]) => `<button class="chip ${f === k ? 'on' : ''}" type="button" data-vf="${k}">${l}<span class="n">${counts[k]}</span></button>`).join('')}</div>
      <div class="grid auto">${shown.map((v) => `<div class="card media">
        <video controls preload="none" playsinline poster="${esc(v.poster || '')}" src="${esc(v.file)}"></video>
        <div class="meta"><div class="t">${topic(v.topic)}<span>${esc(v.title)}</span></div>
          <div class="row">${badge(v.status)}<span>${v.duration}s · ${v.size_mb} Mo</span>${v.link ? `<a href="${esc(v.link)}" target="_blank" rel="noopener">Voir sur Instagram</a>` : ''}</div>
          <div class="row"><span title="${esc(v.file)}">${esc(v.name)}</span></div>
          ${capBlock(v.caption)}</div></div>`).join('')}</div>`;
  }

  function posts() {
    const tab = store.get('nx-pt', 'carousels');
    const cars = D.carousels || [], tips = D.tips || [];
    let body = '';
    if (tab === 'carousels') {
      const grp = [['Prêts à publier', cars.filter((c) => c.status === 'ready')], ['Publiés', cars.filter((c) => c.status === 'published')]];
      body = grp.map(([t, arr]) => `<div class="h2">${t} <small>${arr.length} carrousels</small></div><div class="grid auto">${arr.map((c) => {
        const g = gal(c.slides.map((s, i) => ({ src: s.full, cap: `${c.title} · slide ${i + 1}` })));
        return `<div class="card media carousel"><div class="thumb" data-gal="${g}" data-i="0"><img loading="lazy" src="${esc(c.slides[0].thumb)}" alt="${esc(c.title)}"><span class="count">${c.slides.length} slide${c.slides.length > 1 ? 's' : ''}</span></div>
          ${c.slides.length > 1 ? `<div class="strip">${c.slides.map((s, i) => `<img loading="lazy" src="${esc(s.thumb)}" alt="" data-gal="${g}" data-i="${i}">`).join('')}</div>` : ''}
          <div class="meta"><div class="t">${topic(c.topic)}<span>${esc(c.title)}</span></div><div class="row">${badge(c.status)}<span>${esc(c.id)}</span>${c.link ? `<a href="${esc(c.link)}" target="_blank" rel="noopener">Voir sur Instagram</a>` : ''}</div>${capBlock(c.caption)}</div></div>`;
      }).join('')}</div>`).join('');
    } else {
      const g = gal(tips.map((t) => ({ src: t.full, cap: `${t.id} · ${t.title}` })));
      body = `<div class="grid auto">${tips.map((t, i) => `<div class="card media"><div class="thumb" data-gal="${g}" data-i="${i}"><img loading="lazy" src="${esc(t.thumb)}" alt="${esc(t.title)}"></div>
        <div class="meta"><div class="t">${topic(t.topic)}<span>${esc(t.title)}</span></div><div class="row">${badge(t.status)}<span>${esc(t.id)}</span></div>${capBlock(t.caption)}</div></div>`).join('')}</div>`;
    }
    return head('Posts', 'Carrousels 1080×1350 et « tips du jour ». Clique sur une image pour l’agrandir.') + `
      <div class="chips">${[['carousels', 'Carrousels', cars.length], ['tips', 'Tips du jour', tips.length]].map(([k, l, n]) => `<button class="chip ${tab === k ? 'on' : ''}" type="button" data-pt="${k}">${l}<span class="n">${n}</span></button>`).join('')}</div>${body}`;
  }

  function stories() {
    const st = D.stories || [];
    const block = (t, arr, note) => {
      const g = gal(arr.map((s) => ({ src: s.full, cap: s.title })));
      return `<div class="h2">${t} <small>${note}</small></div><div class="grid auto-s">${arr.map((s, i) => `<div class="card media story"><div class="thumb" data-gal="${g}" data-i="${i}"><img loading="lazy" src="${esc(s.thumb)}" alt="${esc(s.title)}"></div><div class="meta"><div class="t">${esc(s.title)}</div><div class="row">${badge(s.status)}</div></div></div>`).join('')}</div>`;
    };
    const hl = D.highlights || [];
    const g = gal(hl.map((h) => ({ src: h.full, cap: h.title })));
    return head('Stories', 'Format 1080×1920. Les liens cliquables (sticker WhatsApp) s’ajoutent dans l’app, pas par l’API.') +
      block('Prêtes à publier', st.filter((s) => s.status === 'ready'), 'ajouter le sticker lien dans l’app') +
      block('Déjà publiées', st.filter((s) => s.status === 'published'), 'à ranger dans les highlights') +
      `<div class="h2">Couvertures de highlights <small>${hl.length}</small></div><div class="grid auto-s">${hl.map((h, i) => `<div class="card media" style="padding:14px;align-items:center"><div class="thumb" data-gal="${g}" data-i="${i}" style="background:none"><img loading="lazy" src="${esc(h.thumb)}" alt="" style="width:110px;height:110px;border-radius:50%;aspect-ratio:1"></div><div class="t" style="margin-top:10px;text-transform:capitalize">${esc(h.title)}</div></div>`).join('')}</div>`;
  }

  function offre() {
    const p = D.prices || [];
    return head('Offre & prix', 'Grille de départ recommandée (prix TTC, TVA 18 %). Repères tirés de l’étude de marché du document 04.') + `
      <div class="grid g4">${D.business.services.map((s) => `<div class="card svc" style="--c:${TOPIC[s.topic]}"><h3>${esc(s.name)}</h3><p>${esc(s.text)}</p></div>`).join('')}</div>
      <div class="card" style="margin-top:18px;border-color:rgba(255,196,61,0.35)"><div class="h2" style="margin:0 0 6px">${topic('sun')} Offre de lancement</div><p style="color:var(--muted)">${esc(D.business.offer)}. Le Home Check est déduit si le client commande 2 000 ₪ ou plus dans les 30 jours.</p></div>
      <div class="h2">Grille tarifaire NEXORA <small>${p.length} prestations</small></div>
      <div class="tablewrap"><table class="prices"><thead><tr><th>Prestation</th><th>Contenu</th><th>Prix TTC</th><th>Repère marché</th></tr></thead><tbody>
        ${p.map((r) => `<tr><td><div style="display:flex;gap:10px;align-items:flex-start;font-weight:700">${topic(r.topic)}<span>${esc(r.service)}</span></div></td><td style="color:var(--muted)">${esc(r.content)}</td><td><span class="price">${esc(r.price)}</span></td><td style="color:var(--muted)">${esc(r.market)}</td></tr>`).join('')}
      </tbody></table></div>
      <div class="grid g2" style="margin-top:18px">
        <div class="card info"><h3>Règles pour chiffrer</h3><ul class="rules">
          <li>Afficher TTC aux particuliers, HT aux entreprises (TTC = HT × 1,18).</li>
          <li>Se placer au prix médian du marché, pas en low-cost : plus de valeur incluse.</li>
          <li>Matériel : ne jamais dépasser le prix public le plus bas (zap) de plus de 5 %.</li>
          <li>Base interne : 250 ₪ HT de l’heure. Vendre au forfait, pas à l’heure.</li>
          <li>Acompte de 40 à 50 % quand il y a du matériel.</li>
          <li>Travail sur le 230 V : électricien agréé.</li></ul></div>
        <div class="card info"><h3>Ce que NEXORA ajoute</h3><ul class="rules" style="--c:var(--smart)">
          <li>Durcissement cyber (fiche remise au client).</li>
          <li>Garantie main-d’œuvre de 24 mois.</li>
          <li>Dossier de fin de chantier : plan, étiquetage, photos, identifiants remis en privé.</li>
          <li>Carte de couverture Wi-Fi avant/après.</li>
          <li>Commerces : panneau « vidéosurveillance » et durée de conservation réglée.</li></ul></div>
      </div>
      <p class="note">Détail complet, sources et fourchettes : Documents → « 04 · Prix du marché Israël ».</p>`;
  }

  function marque() {
    const colors = [['Navy', '#0F2A44', 'Texte, boutons'], ['Network', '#2F7FD1', 'Réseau & Wi-Fi'], ['Security', '#FF6B4A', 'Caméras'], ['Smart Home', '#12B386', 'Maison connectée'], ['Digital', '#7A5CF5', 'Interphone, dashboards'], ['Soleil', '#FFC43D', 'Home Check, mises en avant'], ['Dégradé 1', '#1E5E9C', 'Début du dégradé logo'], ['Dégradé 2', '#3E95DD', 'Fin du dégradé (fond clair)']];
    const st = D.stills || [];
    const g = gal(st.map((s) => ({ src: s.full, cap: s.title })));
    return head('Marque', 'Logo v2 (direction A « Evolution »), couleurs, polices et visuels 3D réutilisables.') + `
      <div class="h2" style="margin-top:0">Logos <small>SVG vectoriels · clic pour télécharger</small></div>
      <div class="grid auto">${(D.logos || []).map((l) => `<div class="card logo-tile"><div class="pv ${l.white ? 'dark' : ''}"><img loading="lazy" src="${esc(l.svg)}" alt="${esc(l.name)}"></div><div class="row"><span>${esc(l.name)}</span><a class="btn sm" href="${esc(l.svg)}" download>${ICON.dl}SVG</a></div></div>`).join('')}</div>
      <div class="h2">Fichiers PNG <small>photo de profil, favicon, icône d’app…</small></div>
      <div class="card"><div class="chips" style="margin:0">${(D.pngs || []).map((p) => `<a class="chip" href="${esc(p.file)}" download style="text-decoration:none">${esc(p.name)}</a>`).join('')}</div></div>
      <div class="h2">Couleurs <small>clic pour copier le code</small></div>
      <div class="grid auto-s">${colors.map(([n, h, u]) => `<button class="card swatch" type="button" data-hex="${h}" style="--c:${h};text-align:left"><div class="sw"></div><div class="meta"><b>${n}</b><code>${h}</code><div class="note" style="margin-top:4px">${u}</div></div></button>`).join('')}</div>
      <div class="grid g2" style="margin-top:18px">
        <div class="card info"><h3>Polices</h3><p><b style="font-family:var(--head);font-size:26px;color:var(--text)">Bricolage Grotesque</b><br>Titres, gros chiffres.</p><p style="margin-top:12px"><b style="font-size:20px;color:var(--text)">Instrument Sans</b><br>Textes, légendes, interface.</p></div>
        <div class="card info"><h3>Règles</h3><ul class="rules"><li>Une couleur = un service, partout (Instagram, devis, site).</li><li>Zone de protection autour du logo ≥ la largeur du point de connexion. Icône : 20 px minimum.</li><li>Pas de logos Hikvision / Provision-ISR / Reolink sans accord du distributeur : noms en texte seulement.</li><li>Pas de faux boutons dans les stories.</li></ul></div>
      </div>
      <div class="h2">Visuels 3D <small>${st.length} rendus transparents · instagram/assets3d</small></div>
      <div class="grid auto-s">${st.map((s, i) => `<div class="card" style="padding:12px"><div class="still" data-gal="${g}" data-i="${i}" style="cursor:zoom-in"><img loading="lazy" src="${esc(s.full)}" alt="${esc(s.title)}"></div><div style="margin-top:10px;font-weight:700;font-size:13.5px;text-transform:capitalize">${esc(s.title)}</div></div>`).join('')}</div>`;
  }

  function infos() {
    const b = D.business;
    const cmds = [
      ['Mettre à jour l’interface (après de nouveaux fichiers)', 'python HQ\\build_hq.py'],
      ['Mettre à jour les stats Instagram', 'powershell -ExecutionPolicy Bypass -File HQ\\update_stats.ps1'],
      ['Rendre une vidéo', 'cd video ; node render.js projects/rl08-ethernet-rooms --lang en'],
      ['Régénérer les posts et stories du batch 2', 'cd instagram\\src2 ; python batch2.py'],
      ['Régénérer les posts du batch 1', 'cd instagram\\src2 ; python build.py'],
    ];
    return head('Infos utiles', 'Contacts, fournisseurs, règles de communication, limites techniques et commandes.') + `
      <div class="grid g2">
        <div class="card info"><h3>Contact & liens</h3><dl class="kv">
          <dt>WhatsApp</dt><dd><a href="${esc(b.wa)}" target="_blank" rel="noopener">${esc(b.whatsapp)}</a></dd>
          <dt>Instagram</dt><dd><a href="${esc(b.ig_url)}" target="_blank" rel="noopener">${esc(b.instagram)}</a></dd>
          <dt>E-mail</dt><dd><a href="mailto:${esc(b.email)}">${esc(b.email)}</a></dd>
          <dt>Médias en ligne</dt><dd><a href="${esc(b.assets_repo)}" target="_blank" rel="noopener">github.com/nexoraraanana/nexora-assets</a></dd>
          <dt>Zone</dt><dd>${esc(b.city)}</dd>
          <dt>Langues</dt><dd>${esc(b.languages)}</dd></dl></div>
        <div class="card info"><h3>Marques & fournisseur</h3><dl class="kv">
          <dt>Marques</dt><dd>${b.brands.map(esc).join(' · ')}</dd>
          <dt>Fournisseur</dt><dd>${esc(b.supplier)}</dd>
          <dt>Argument</dt><dd>Provision-ISR est une marque israélienne (Kfar Saba). Installation « durcie » dans tous les cas.</dd>
          <dt>Fiches</dt><dd>Documents → « 05 · Fiches caméras & règles »</dd></dl></div>
        <div class="card info"><h3>Ce qu’on peut dire</h3><ul class="rules" style="--c:var(--smart)">
          <li>« Up to 4K » / « jusqu’à 4K », toujours « selon le modèle ».</li>
          <li>Détection personne / véhicule et vision nocturne couleur : « selon le modèle ».</li>
          <li>Caméras PoE filaires : ne peuvent pas être brouillées comme le Wi-Fi.</li>
          <li>Réseau privé, pas exposé sur internet ; enregistrement local, sans abonnement.</li>
          <li>Ouverture du portail : « avec un portail ou une serrure électrique compatible ».</li></ul></div>
        <div class="card info"><h3>À éviter</h3><ul class="rules no">
          <li>« Impossible à pirater » : faux. Dire « durci », « réseau séparé », « pas exposé ».</li>
          <li>Promettre la 4K ou la couleur la nuit sans préciser le modèle.</li>
          <li>Dire que toutes les caméras Wi-Fi se rechargent (seulement les modèles sur batterie).</li>
          <li>Inventer des prix ou des chiffres : tout chiffre doit avoir une source.</li>
          <li>Publier pendant Shabbat et les fêtes.</li></ul></div>
        <div class="card info"><h3>Limites de l’API Instagram</h3><ul class="rules" style="--c:var(--sun)">
          <li>Pas de suppression ni de modification d’image d’un post publié.</li>
          <li>Pas d’épinglage, pas de lieu, pas de highlights.</li>
          <li>Stories : pas de sticker lien (à faire dans l’app).</li>
          <li>Reels : vidéos hébergées via jsDelivr (le dépôt GitHub sert les images).</li></ul></div>
        <div class="card info"><h3>Outils</h3><dl class="kv">
          <dt>Composio</dt><dd>Instagram, Canva, GitHub, Gmail / Drive</dd>
          <dt>ElevenLabs</dt><dd>Voix (Liam par défaut). Compte gratuit : 10 000 caractères par mois.</dd>
          <dt>Vidéos</dt><dd>three.js + Chrome + ffmpeg (dossier <code>video/</code>)</dd>
          <dt>Posts</dt><dd>HTML → Chrome → JPG (<code>instagram/src2/</code>)</dd>
          <dt>Modèles 3D</dt><dd>Poly Haven (CC0), Poly Pizza / Paciorek (CC-BY) : crédits dans <code>video/models/ATTRIBUTION.txt</code></dd></dl></div>
      </div>
      <div class="h2">Commandes <small>à lancer depuis le dossier Nexora</small></div>
      <div class="grid g2">${cmds.map(([l, c], i) => `<div class="card" style="padding:16px 18px"><div style="font-weight:700;font-size:14px">${esc(l)}</div><div class="cmd"><code>${esc(c)}</code><button class="btn sm" type="button" data-cmd="${i}">${ICON.copy}</button></div></div>`).join('')}</div>`;
  }

  function docs() {
    const list = D.docs || [];
    const cur = store.get('nx-doc', list[0] && list[0].id);
    const d = list.find((x) => x.id === cur) || list[0];
    if (!d) return head('Documents', '') + '<div class="card empty"><b>Aucun document</b></div>';
    return head('Documents', 'Les fichiers du projet, lisibles ici. Pour les modifier : ouvre le fichier .md dans le dossier Nexora.') + `
      <div class="docs"><div class="card doclist">${list.map((x) => `<button type="button" class="${x.id === d.id ? 'on' : ''}" data-doc="${esc(x.id)}">${esc(x.title)}</button>`).join('')}</div>
      <article class="card"><div class="docmeta"><span>${esc(d.file)}</span><span>modifié le ${esc(d.updated)}</span></div><div class="prose">${d.html}</div></article></div>`;
  }

  function journal() {
    const j = (D.journal || []).slice().reverse();
    return head('Journal', 'Tout ce qui a été fait, du plus récent au plus ancien (tiré du document 00).') +
      `<div class="timeline">${j.map((e) => `<div class="card ev"><div class="d">${esc(e.date)}</div><div class="x">${e.html}</div></div>`).join('')}</div>`;
  }

  function cameras() {
    const db = D.cameras || { cameras: [], types: {} };
    const list = db.cameras || [];
    const f = store.get('nx-cf', 'all');
    const brands = [...new Set(list.map((c) => c.brand))];
    const shown = list.filter((c) => f === 'all' || c.brand === f);
    const g = gal(shown.map((c) => ({ src: c.full, cap: `${c.brand} · ${c.type_label}` })));
    return head('Caméras', 'Base de données des modèles (catalogue/cameras.json). Nouvelles images : les déposer dans « image cameras » puis lancer <code>python catalogue/import_cameras.py</code>.') + `
      <div class="chips">${[['all', 'Toutes', list.length], ...brands.map((b) => [b, b, list.filter((c) => c.brand === b).length])].map(([k, l, n]) => `<button class="chip ${f === k ? 'on' : ''}" type="button" data-cf="${esc(k)}">${esc(l)}<span class="n">${n}</span></button>`).join('')}</div>
      <div class="grid auto">${shown.map((c, i) => `<div class="card media">
        <div class="thumb prod" data-gal="${g}" data-i="${i}"><img loading="lazy" src="${esc(c.full)}" alt="${esc(c.brand + ' ' + c.type_label)}"></div>
        <div class="meta"><div class="t">${topic(c.brand_id === 'hikvision' ? 'security' : 'digital')}<span>${esc(c.brand)} · ${esc(c.type_label)}</span></div>
          <div class="row"><span class="badge st-ready">${esc(c.model || c.model_note)}</span><span>${esc(c.id)}</span></div>
          <p style="font-size:13.5px;color:var(--muted)">${esc(c.use)}</p>
          ${(c.seen || []).length ? `<ul class="rules" style="--c:var(--network);gap:4px">${c.seen.map((s) => `<li style="font-size:13px">${esc(s)}</li>`).join('')}</ul>` : ''}
          <div class="row"><span title="${esc(c.original)}">${esc(c.image)}</span></div></div></div>`).join('')}</div>
      <div class="h2">Quel type pour quel endroit</div>
      <div class="grid g2">${Object.values(db.types || {}).map((t) => `<div class="card info"><h3>${esc(t.label)}</h3><p>${esc(t.use)}</p></div>`).join('')}</div>
      <p class="note">Les références exactes (ex. DS-2CD…, DI-…) sont à compléter dans cameras.json : les specs ne s'affichent pas tant que le modèle n'est pas confirmé.</p>`;
  }

  const RENDER = { accueil, instagram, videos, posts, stories, cameras, offre, marque, infos, docs, journal };
  if (D.public) {
    const keep = ['accueil', 'videos', 'posts', 'stories', 'marque'];
    for (let i = SECTIONS.length - 1; i >= 0; i--) if (!keep.includes(SECTIONS[i][0])) SECTIONS.splice(i, 1);
    Object.keys(RENDER).forEach((k) => { if (!keep.includes(k)) delete RENDER[k]; });
  }

  // ---------- shell ----------
  function nav() {
    $('#nav').innerHTML = SECTIONS.map(([id, label, icon, count]) => `<a href="#${id}" data-nav="${id}">${icon}<span>${label}</span>${count != null ? `<span class="count ${id === 'videos' || id === 'posts' || id === 'stories' ? '' : ''}">${esc(count)}</span>` : ''}</a>`).join('');
    $('#built').innerHTML = `Données : ${esc(D.generated_at || '—')}<br>${nReady} contenus prêts, non publiés`;
  }
  function route() {
    const id = (location.hash || '#accueil').slice(1);
    const sec = RENDER[id] ? id : 'accueil';
    CAPS = []; GALLERIES = [];
    const main = $('#main');
    main.innerHTML = `<section class="section on" id="s-${sec}">${RENDER[sec]()}</section>`;
    document.querySelectorAll('[data-nav]').forEach((a) => a.classList.toggle('on', a.dataset.nav === sec));
    const on = document.querySelector('[data-nav].on');
    if (on && window.innerWidth <= 900) on.scrollIntoView({ inline: 'center', block: 'nearest' });
    document.title = `NEXORA HQ · ${SECTIONS.find((s) => s[0] === sec)[1]}`;
    window.scrollTo(0, 0);
  }

  document.addEventListener('click', (e) => {
    const t = e.target.closest('[data-copy],[data-vf],[data-pt],[data-cf],[data-doc],[data-hex],[data-cmd],[data-gal]');
    if (!t) return;
    if (t.dataset.copy != null) copy(CAPS[+t.dataset.copy], 'Légende copiée');
    else if (t.dataset.vf) { store.set('nx-vf', t.dataset.vf); route(); }
    else if (t.dataset.pt) { store.set('nx-pt', t.dataset.pt); route(); }
    else if (t.dataset.cf) { store.set('nx-cf', t.dataset.cf); route(); }
    else if (t.dataset.doc) { store.set('nx-doc', t.dataset.doc); route(); }
    else if (t.dataset.hex) copy(t.dataset.hex, `${t.dataset.hex} copié`);
    else if (t.dataset.cmd != null) copy(t.closest('.cmd').querySelector('code').textContent, 'Commande copiée');
    else if (t.dataset.gal != null) openLB(GALLERIES[+t.dataset.gal], +t.dataset.i || 0);
  });
  document.addEventListener('change', (e) => {
    const t = e.target;
    if (t.dataset && t.dataset.todo) { const d = store.get('nx-todo', {}); d[t.dataset.todo] = t.checked; store.set('nx-todo', d); }
  });
  $('#lbX').onclick = closeLB; $('#lbPrev').onclick = () => stepLB(-1); $('#lbNext').onclick = () => stepLB(1);
  $('#lb').addEventListener('click', (e) => { if (e.target.id === 'lb') closeLB(); });
  document.addEventListener('keydown', (e) => {
    if ($('#lb').hidden) return;
    if (e.key === 'Escape') closeLB(); else if (e.key === 'ArrowLeft') stepLB(-1); else if (e.key === 'ArrowRight') stepLB(1);
  });
  $('#themeBtn').onclick = () => {
    const cur = document.documentElement.dataset.theme === 'light' ? 'dark' : 'light';
    document.documentElement.dataset.theme = cur;
    try { localStorage.setItem('nx-theme', cur); } catch (err) { /* ignore */ }
  };
  window.addEventListener('hashchange', route);
  if (!window.NX) { document.getElementById('main').innerHTML = '<div class="card empty"><b>data.js manquant</b>Lance python HQ\\build_hq.py</div>'; return; }
  nav(); route();
})();
